// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockBalanceRepository is an autogenerated mock type for the BalanceRepository type
type MockBalanceRepository struct {
	mock.Mock
}

type MockBalanceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceRepository) EXPECT() *MockBalanceRepository_Expecter {
	return &MockBalanceRepository_Expecter{mock: &_m.Mock}
}

// LockBalance provides a mock function with given fields: ctx, userID
func (_m *MockBalanceRepository) LockBalance(ctx context.Context, userID uint64) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for LockBalance")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBalanceRepository_LockBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockBalance'
type MockBalanceRepository_LockBalance_Call struct {
	*mock.Call
}

// LockBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockBalanceRepository_Expecter) LockBalance(ctx interface{}, userID interface{}) *MockBalanceRepository_LockBalance_Call {
	return &MockBalanceRepository_LockBalance_Call{Call: _e.mock.On("LockBalance", ctx, userID)}
}

func (_c *MockBalanceRepository_LockBalance_Call) Run(run func(ctx context.Context, userID uint64)) *MockBalanceRepository_LockBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockBalanceRepository_LockBalance_Call) Return(_a0 int64, _a1 error) *MockBalanceRepository_LockBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBalanceRepository_LockBalance_Call) RunAndReturn(run func(context.Context, uint64) (int64, error)) *MockBalanceRepository_LockBalance_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBalance provides a mock function with given fields: ctx, userID, balance
func (_m *MockBalanceRepository) UpdateBalance(ctx context.Context, userID uint64, balance int64) error {
	ret := _m.Called(ctx, userID, balance)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int64) error); ok {
		r0 = rf(ctx, userID, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBalanceRepository_UpdateBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBalance'
type MockBalanceRepository_UpdateBalance_Call struct {
	*mock.Call
}

// UpdateBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - balance int64
func (_e *MockBalanceRepository_Expecter) UpdateBalance(ctx interface{}, userID interface{}, balance interface{}) *MockBalanceRepository_UpdateBalance_Call {
	return &MockBalanceRepository_UpdateBalance_Call{Call: _e.mock.On("UpdateBalance", ctx, userID, balance)}
}

func (_c *MockBalanceRepository_UpdateBalance_Call) Run(run func(ctx context.Context, userID uint64, balance int64)) *MockBalanceRepository_UpdateBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(int64))
	})
	return _c
}

func (_c *MockBalanceRepository_UpdateBalance_Call) Return(_a0 error) *MockBalanceRepository_UpdateBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBalanceRepository_UpdateBalance_Call) RunAndReturn(run func(context.Context, uint64, int64) error) *MockBalanceRepository_UpdateBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBalanceRepository creates a new instance of MockBalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceRepository {
	mock := &MockBalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
