// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "entaintest/internal/repository/model"

	mock "github.com/stretchr/testify/mock"
)

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function with given fields: ctx, transaction
func (_m *MockTransactionRepository) Insert(ctx context.Context, transaction model.Transaction) error {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Transaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockTransactionRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction model.Transaction
func (_e *MockTransactionRepository_Expecter) Insert(ctx interface{}, transaction interface{}) *MockTransactionRepository_Insert_Call {
	return &MockTransactionRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, transaction)}
}

func (_c *MockTransactionRepository_Insert_Call) Run(run func(ctx context.Context, transaction model.Transaction)) *MockTransactionRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Transaction))
	})
	return _c
}

func (_c *MockTransactionRepository_Insert_Call) Return(_a0 error) *MockTransactionRepository_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_Insert_Call) RunAndReturn(run func(context.Context, model.Transaction) error) *MockTransactionRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
