// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "entaintest/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockWalletRepo is an autogenerated mock type for the WalletRepo type
type MockWalletRepo struct {
	mock.Mock
}

type MockWalletRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletRepo) EXPECT() *MockWalletRepo_Expecter {
	return &MockWalletRepo_Expecter{mock: &_m.Mock}
}

// ApplyTransaction provides a mock function with given fields: ctx, transaction
func (_m *MockWalletRepo) ApplyTransaction(ctx context.Context, transaction model.Transaction) (int64, error) {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for ApplyTransaction")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Transaction) (int64, error)); ok {
		return rf(ctx, transaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Transaction) int64); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Transaction) error); ok {
		r1 = rf(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepo_ApplyTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyTransaction'
type MockWalletRepo_ApplyTransaction_Call struct {
	*mock.Call
}

// ApplyTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction model.Transaction
func (_e *MockWalletRepo_Expecter) ApplyTransaction(ctx interface{}, transaction interface{}) *MockWalletRepo_ApplyTransaction_Call {
	return &MockWalletRepo_ApplyTransaction_Call{Call: _e.mock.On("ApplyTransaction", ctx, transaction)}
}

func (_c *MockWalletRepo_ApplyTransaction_Call) Run(run func(ctx context.Context, transaction model.Transaction)) *MockWalletRepo_ApplyTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Transaction))
	})
	return _c
}

func (_c *MockWalletRepo_ApplyTransaction_Call) Return(_a0 int64, _a1 error) *MockWalletRepo_ApplyTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepo_ApplyTransaction_Call) RunAndReturn(run func(context.Context, model.Transaction) (int64, error)) *MockWalletRepo_ApplyTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function with given fields: ctx, userID
func (_m *MockWalletRepo) GetBalance(ctx context.Context, userID uint64) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepo_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockWalletRepo_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockWalletRepo_Expecter) GetBalance(ctx interface{}, userID interface{}) *MockWalletRepo_GetBalance_Call {
	return &MockWalletRepo_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID)}
}

func (_c *MockWalletRepo_GetBalance_Call) Run(run func(ctx context.Context, userID uint64)) *MockWalletRepo_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockWalletRepo_GetBalance_Call) Return(_a0 int64, _a1 error) *MockWalletRepo_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepo_GetBalance_Call) RunAndReturn(run func(context.Context, uint64) (int64, error)) *MockWalletRepo_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletRepo creates a new instance of MockWalletRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletRepo {
	mock := &MockWalletRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
