// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	request "entaintest/internal/service/model/request"

	response "entaintest/internal/service/model/response"
)

// MockTransactionService is an autogenerated mock type for the TransactionService type
type MockTransactionService struct {
	mock.Mock
}

type MockTransactionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionService) EXPECT() *MockTransactionService_Expecter {
	return &MockTransactionService_Expecter{mock: &_m.Mock}
}

// ProcessTransaction provides a mock function with given fields: ctx, _a1
func (_m *MockTransactionService) ProcessTransaction(ctx context.Context, _a1 request.ProcessTransactionRequest) (*response.ProcessTransactionResponse, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ProcessTransaction")
	}

	var r0 *response.ProcessTransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.ProcessTransactionRequest) (*response.ProcessTransactionResponse, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.ProcessTransactionRequest) *response.ProcessTransactionResponse); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ProcessTransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.ProcessTransactionRequest) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_ProcessTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessTransaction'
type MockTransactionService_ProcessTransaction_Call struct {
	*mock.Call
}

// ProcessTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 request.ProcessTransactionRequest
func (_e *MockTransactionService_Expecter) ProcessTransaction(ctx interface{}, _a1 interface{}) *MockTransactionService_ProcessTransaction_Call {
	return &MockTransactionService_ProcessTransaction_Call{Call: _e.mock.On("ProcessTransaction", ctx, _a1)}
}

func (_c *MockTransactionService_ProcessTransaction_Call) Run(run func(ctx context.Context, _a1 request.ProcessTransactionRequest)) *MockTransactionService_ProcessTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.ProcessTransactionRequest))
	})
	return _c
}

func (_c *MockTransactionService_ProcessTransaction_Call) Return(_a0 *response.ProcessTransactionResponse, _a1 error) *MockTransactionService_ProcessTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_ProcessTransaction_Call) RunAndReturn(run func(context.Context, request.ProcessTransactionRequest) (*response.ProcessTransactionResponse, error)) *MockTransactionService_ProcessTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionService creates a new instance of MockTransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionService {
	mock := &MockTransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
